### ISSUE TITLE
Command install: parameter --replaceHtaccessFile=no doesn't work

### ISSUE THREAD

**Issue by mzeis** [netz98/n98-magerun2#191]
When trying to automatically answer the question

    Write BaseURL to .htaccess file? [n]

with "no" by passing `--replaceHtaccessFile=no`, I'm still asked.

I assume this happens because in https://github.com/netz98/n98-magerun2/blob/3523cb80728ba87c5e87ae75af24e54e76ba2e94/src/N98/Magento/Command/Installer/SubCommand/RewriteHtaccessFile.php#L24 the question will only be skipped if I specify a value that converts to true.

By the way, after checking the code I assume that this also happens in n98-magerun (https://github.com/netz98/n98-magerun/blob/0c8d1b9b630f2b93a00da77ad5e43fd2f56bdb90/src/N98/Magento/Command/Installer/InstallCommand.php#L863) but I didn't try it there.

**Comment by tkn98** [comment]
Thanks for your report. This is correct, [the argument is optional](https://github.com/netz98/n98-magerun/blob/0c8d1b9b630f2b93a00da77ad5e43fd2f56bdb90/src/N98/Magento/Command/Installer/InstallCommand.php#L80) but it's optionality is not checked.

**Comment by ktomk** [comment]
@mzeis: Do you plan to do a PR to fix this? Just want to know for planning. Thanks :)

**Comment by mzeis** [comment]
@ktomk I can't give a timeline on it, that's why I didn't commit to do it. :-) If this is not a big problem then you can assign the issue to me.

**Comment by tkn98** [comment]
@mzeis: No worries, it's patched in development right now. Thanks for taking the time to report it. Please get the latest development version and let me know if it works for you now.

**Comment by ktomk** [comment]
@mzeis: While at work (the other account), I was that much in a hurry that I misread your comment. It's not a big problem, so I just could have assigned you, but instead I misread it and I had the wrong impression that your shedule is too tight. So I just patched it. Sorry, I didn't wanted to push you away. So please check if the develop version works (`n98-magerun2.phar self-update --unstable`, use w/o the switch to fall back to last stable).

**Comment by ktomk** [comment]
I think the fix is well now, I also compared and streamlined with a similar sub-command in the installer so I'm pretty optimistic this is fixed. Will be part of the next release which should be available soon. Just report back if there are still issues, I consider it closed until further notice.

**Comment by ktomk** [comment]
Released with 1.1.7.

**Comment by mzeis** [comment]
Hi,

wow that was quick, thanks!

I'm afraid I'm still getting asked. I can skip the sample data question though when providing this parameter the same way:
 
    $ wget https://files.magerun.net/n98-magerun2.phar
    $ chmod +x n98-magerun2.phar
    $ ./n98-magerun2.phar --version
    n98-magerun2 version 1.1.7 by netz98 new media GmbH
    
    $ ./n98-magerun2.phar install --replaceHtaccessFile=no --installSampleData=no
    ....
    For security, remove write permissions from these directories: '/tmp/magento/app/etc'
    [Progress: 308 / 308]
    [SUCCESS]: Magento installation complete.
    [SUCCESS]: Magento Admin URI: /admin
    Write BaseURL to .htaccess file? [n]: n
    Reindex all after installation

**Comment by ktomk** [comment]
@mzeis: Ok, thanks for the re-report. The build is broken. It should offer magento-ce-2.0.5 as first package but it does not. I can't say what's broken yet in the build process and have to take a look first.

**Comment by ktomk** [comment]
@mzeis: The build has been fixed. You should now be able to update to the fixed version. Please test again.

**Comment by ktomk** [comment]
@mzeis: (sorry, again) The build has been fixed. You should now be able to update to the fixed version. Please test again. My own checks looked good so far now.

**Comment by mzeis** [comment]
Sorry to ask this, but did you get asked the question if you didn't specify the flag and did you get a `.dist` copy of the .htaccess file when specifying `--replaceHtaccessFile=yes`? I tried all variants with a re-downloaded PHAR file and didn't get it...

**Comment by ktomk** [comment]
@mzeis: I didn't test all permutations. And I never checked the htaccess file actually, just running the command with the flag. `--replaceHtaccessFile=no` should prevent to ask in any case, at least according to current code in master (src/N98/Magento/Command/Installer/SubCommand/RewriteHtaccessFile.php:17).

**Comment by ktomk** [comment]
@mzeis: Can you please provide a command-line so I can check if I can reproduce it?

**Comment by mzeis** [comment]
I re-tried it with the newest version:

    wget https://files.magerun.net/n98-magerun2.phar
    chmod +x ./n98-magerun2.phar

Results:

* `./n98-magerun2.phar install`: no question, `.htaccess` is not replaced
* `./n98-magerun2.phar install --replaceHtaccessFile="no"`: no question, `.htaccess` is not replaced
* `./n98-magerun2.phar install --replaceHtaccessFile="yes"`: no question, `.htaccess` is replaced

Is it intended that the first variant doesn't ask you "Write BaseURL to .htaccess file?"? Then the issue can be closed, I guess.

**Comment by ktomk** [comment]
@mzeis: Most likely not. But when I enter `./n98-magerun2.phar install` there is no installation at all unless I answer some more other questions. You've not documented these for reproduction which makes it hard to follow your issue. Please complete the report with additional parameters and text of each question asked and the values you entered if you're doing this interactively (discouraged).

**Comment by mzeis** [comment]
@ktom: I wanted to make this easier to reproduce by showing the effect of the parameter with the most simple command possible. Of course I can specify other parameters like the database name etc. but it won't make any difference regarding the parameter ´--replaceHtaccessFile´.

For the sake of completeness, here is an example:

    [03:51 PM]-[user@vm]-[/tmp]
    $ wget https://files.magerun.net/n98-magerun2.phar
    --2016-05-29 15:51:22--  https://files.magerun.net/n98-magerun2.phar
    Resolving files.magerun.net (files.magerun.net)... 5.35.244.165, 5.35.244.165
    Connecting to files.magerun.net (files.magerun.net)|5.35.244.165|:443... connected.
    HTTP request sent, awaiting response... 200 OK
    Length: 3854972 (3.7M) [application/octet-stream]
    Saving to: `n98-magerun2.phar'
    
    100%[=========================================================================================>] 3,854,972   4.32M/s   in 0.9s
    
    2016-05-29 15:51:23 (4.32 MB/s) - `n98-magerun2.phar' saved [3854972/3854972]
    
    
    [03:51 PM]-[user@vm]-[/tmp]
    $ chmod +x ./n98-magerun2.phar
    
    [03:51 PM]-[user@vm]-[/tmp]
    $ ./n98-magerun2.phar --version
    n98-magerun2 version 1.1.14 by netz98 new media GmbH
    
    [03:51 PM]-[user@vm]-[/tmp]
    $ ./n98-magerun2.phar install --magentoVersion="1" --installationFolder="./magento" --dbHost="localhost" --dbUser="root" --dbPass="123456" --dbName="test" --dbPort="3306" --baseUrl="http://www.test.tld/"
    
    
      Magento 2 Installation
    
    
    Found executable composer
    
    Installing magento/project-community-edition (2.0.6)
      - Installing magento/project-community-edition (2.0.6)
        Loading from cache
    
    Created project in /tmp/magento
    Loading composer repositories with package information
    Installing dependencies (including require-dev)
      - Installing magento/magento-composer-installer (0.1.9)
        Loading from cache
    
      - Installing magento/framework (100.0.8)
        Loading from cache
    
      - Installing magento/language-zh_hans_cn (100.0.5)
        Loading from cache
    
      - Installing magento/language-pt_br (100.0.5)
        Loading from cache
    
      - Installing magento/language-nl_nl (100.0.5)
        Loading from cache
    
      - Installing magento/language-fr_fr (100.0.5)
        Loading from cache
    
      - Installing magento/language-es_es (100.0.5)
        Loading from cache
    
      - Installing magento/language-en_us (100.0.5)
        Loading from cache
    
      - Installing magento/language-de_de (100.0.5)
        Loading from cache
    
      - Installing magento/theme-frontend-blank (100.0.5)
        Loading from cache
    
      - Installing magento/theme-frontend-luma (100.0.5)
        Loading from cache
    
      - Installing magento/theme-adminhtml-backend (100.0.5)
        Loading from cache
    
      - Installing magento/module-media-storage (100.0.5)
        Loading from cache
    
      - Installing magento/module-config (100.0.5)
        Loading from cache
    
      - Installing magento/module-require-js (100.0.5)
        Loading from cache
    
      - Installing magento/module-variable (100.0.5)
        Loading from cache
    
      - Installing magento/module-store (100.0.6)
        Loading from cache
    
      - Installing magento/module-ui (100.0.5)
        Loading from cache
    
      - Installing magento/module-user (100.0.5)
        Loading from cache
    
      - Installing magento/module-email (100.0.5)
        Loading from cache
    
      - Installing magento/module-backend (100.0.7)
        Loading from cache
    
      - Installing magento/module-translation (100.0.5)
        Loading from cache
    
      - Installing magento/module-theme (100.0.5)
        Loading from cache
    
      - Installing magento/module-widget (100.0.6)
        Loading from cache
    
      - Installing magento/module-quote (100.0.6)
        Loading from cache
    
      - Installing magento/module-catalog-inventory (100.0.5)
        Loading from cache
    
      - Installing magento/module-developer (100.0.5)
        Loading from cache
    
      - Installing magento/module-customer (100.0.6)
        Loading from cache
    
      - Installing magento/module-integration (100.0.6)
        Loading from cache
    
      - Installing magento/module-authorization (100.0.5)
        Loading from cache
    
      - Installing magento/module-page-cache (100.0.6)
        Loading from cache
    
      - Installing magento/module-tax (100.0.5)
        Loading from cache
    
      - Installing magento/module-catalog (100.0.7)
        Loading from cache
    
      - Installing magento/module-configurable-product (100.0.5)
        Loading from cache
    
      - Installing magento/module-eav (100.0.5)
        Loading from cache
    
      - Installing magento/module-url-rewrite (100.0.5)
        Loading from cache
    
      - Installing magento/module-cms-url-rewrite (100.0.5)
        Loading from cache
    
      - Installing magento/module-catalog-url-rewrite (100.0.5)
        Loading from cache
    
      - Installing magento/module-import-export (100.0.5)
        Loading from cache
    
      - Installing magento/module-reports (100.0.5)
        Loading from cache
    
      - Installing magento/module-sales-rule (100.0.5)
        Loading from cache
    
      - Installing magento/module-rule (100.0.5)
        Loading from cache
    
      - Installing magento/module-catalog-rule (100.0.5)
        Loading from cache
    
      - Installing magento/module-directory (100.0.5)
        Loading from cache
    
      - Installing magento/module-payment (100.0.6)
        Loading from cache
    
      - Installing magento/module-checkout (100.0.6)
        Loading from cache
    
      - Installing magento/module-msrp (100.0.5)
        Loading from cache
    
      - Installing magento/module-grouped-product (100.0.5)
        Loading from cache
    
      - Installing magento/module-shipping (100.0.5)
        Loading from cache
    
      - Installing magento/module-sales (100.0.7)
        Loading from cache
    
      - Installing magento/module-wishlist (100.0.5)
        Loading from cache
    
      - Installing magento/module-gift-message (100.0.5)
        Loading from cache
    
      - Installing magento/module-sales-sequence (100.0.5)
        Loading from cache
    
      - Installing magento/module-rss (100.0.5)
        Loading from cache
    
      - Installing magento/module-cms (100.0.5)
        Loading from cache
    
      - Installing magento/module-contact (100.0.5)
        Loading from cache
    
      - Installing magento/module-downloadable (100.0.5)
        Loading from cache
    
      - Installing magento/module-cron (100.0.5)
        Loading from cache
    
      - Installing magento/module-newsletter (100.0.6)
        Loading from cache
    
      - Installing magento/module-review (100.0.5)
        Loading from cache
    
      - Installing magento/module-catalog-import-export (100.0.6)
        Loading from cache
    
      - Installing magento/module-product-alert (100.0.5)
        Loading from cache
    
      - Installing magento/module-indexer (100.0.5)
        Loading from cache
    
      - Installing magento/module-backup (100.0.6)
        Loading from cache
    
      - Installing magento/module-weee (100.0.5)
        Loading from cache
    
      - Installing magento/module-webapi-security (100.0.1)
        Loading from cache
    
      - Installing magento/module-webapi (100.0.6)
        Loading from cache
    
      - Installing magento/module-version (100.0.5)
        Loading from cache
    
      - Installing magento/module-usps (100.0.5)
        Loading from cache
    
      - Installing magento/module-ups (100.0.5)
        Loading from cache
    
      - Installing magento/module-tax-import-export (100.0.5)
        Loading from cache
    
      - Installing magento/module-swatches (100.0.6)
        Loading from cache
    
      - Installing magento/module-swagger (100.0.5)
        Loading from cache
    
      - Installing magento/module-sitemap (100.0.5)
        Loading from cache
    
      - Installing magento/module-send-friend (100.0.5)
        Loading from cache
    
      - Installing magento/module-search (100.0.5)
        Loading from cache
    
      - Installing magento/module-catalog-search (100.0.5)
        Loading from cache
    
      - Installing magento/module-sample-data (100.0.5)
        Loading from cache
    
      - Installing justinrainbow/json-schema (1.6.1)
        Loading from cache
    
      - Installing magento/module-product-video (100.0.5)
        Loading from cache
    
      - Installing magento/module-persistent (100.0.5)
        Loading from cache
    
      - Installing magento/module-paypal (100.0.6)
        Loading from cache
    
      - Installing magento/module-offline-shipping (100.0.5)
        Loading from cache
    
      - Installing magento/module-offline-payments (100.0.6)
        Loading from cache
    
      - Installing magento/module-new-relic-reporting (100.0.5)
        Loading from cache
    
      - Installing magento/module-multishipping (100.0.5)
        Loading from cache
    
      - Installing magento/module-layered-navigation (100.0.5)
        Loading from cache
    
      - Installing magento/module-grouped-import-export (100.0.5)
        Loading from cache
    
      - Installing magento/module-cookie (100.0.5)
        Loading from cache
    
      - Installing magento/module-google-analytics (100.0.5)
        Loading from cache
    
      - Installing magento/module-google-optimizer (100.0.5)
        Loading from cache
    
      - Installing magento/module-google-adwords (100.0.5)
        Loading from cache
    
      - Installing magento/module-fedex (100.0.5)
        Loading from cache
    
      - Installing magento/module-encryption-key (100.0.5)
        Loading from cache
    
      - Installing magento/module-downloadable-import-export (100.0.5)
        Loading from cache
    
      - Installing magento/module-dhl (100.0.5)
        Loading from cache
    
      - Installing magento/module-deploy (100.0.6)
        Loading from cache
    
      - Installing magento/module-customer-import-export (100.0.5)
        Loading from cache
    
      - Installing magento/module-currency-symbol (100.0.5)
        Loading from cache
    
      - Installing magento/module-configurable-import-export (100.0.5)
        Loading from cache
    
      - Installing magento/module-checkout-agreements (100.0.5)
        Loading from cache
    
      - Installing magento/module-catalog-widget (100.0.5)
        Loading from cache
    
      - Installing magento/module-catalog-rule-configurable (100.0.5)
        Loading from cache
    
      - Installing magento/module-captcha (100.0.7)
        Loading from cache
    
      - Installing magento/module-cache-invalidate (100.0.5)
        Loading from cache
    
      - Installing magento/module-bundle (100.0.5)
        Loading from cache
    
      - Installing magento/module-bundle-import-export (100.0.5)
        Loading from cache
    
      - Installing braintree/braintree_php (2.39.0)
        Loading from cache
    
      - Installing magento/module-braintree (100.0.6)
        Loading from cache
    
      - Installing magento/module-authorizenet (100.0.6)
        Loading from cache
    
      - Installing magento/module-advanced-pricing-import-export (100.0.6)
        Loading from cache
    
      - Installing magento/module-admin-notification (100.0.5)
        Loading from cache
    
      - Installing magento/module-marketplace (100.0.5)
        Loading from cache
    
      - Installing symfony/console (v2.6.13)
        Loading from cache
    
      - Installing symfony/process (v2.8.6)
        Loading from cache
    
      - Installing symfony/finder (v2.8.6)
        Loading from cache
    
      - Installing seld/jsonlint (1.4.0)
        Loading from cache
    
      - Installing composer/composer (1.0.0-alpha10)
        Loading from cache
    
      - Installing magento/composer (1.0.2)
        Loading from cache
    
      - Installing symfony/filesystem (v2.8.6)
        Loading from cache
    
      - Installing tedivm/jshrink (v1.0.1)
        Loading from cache
    
      - Installing phpseclib/phpseclib (0.3.10)
        Loading from cache
    
      - Installing symfony/event-dispatcher (v2.8.6)
        Loading from cache
    
      - Installing tubalmartin/cssmin (v2.4.8-p4)
        Loading from cache
    
      - Installing pelago/emogrifier (v0.1.1)
        Loading from cache
    
      - Installing oyejorge/less.php (v1.7.0.3)
        Loading from cache
    
      - Installing psr/log (1.0.0)
        Loading from cache
    
      - Installing monolog/monolog (1.16.0)
        Loading from cache
    
      - Installing colinmollenhour/credis (1.6)
        Loading from cache
    
      - Installing magento/zendframework1 (1.12.16)
        Loading from cache
    
      - Installing colinmollenhour/php-redis-session-abstract (v1.1)
        Loading from cache
    
      - Installing zendframework/zend-stdlib (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-validator (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-escaper (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-uri (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-loader (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-http (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-servicemanager (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-log (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-math (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-json (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-serializer (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-eventmanager (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-code (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-di (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-filter (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-inputfilter (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-form (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-config (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-view (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-i18n (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-text (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-mvc (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-modulemanager (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-console (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-crypt (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-server (2.4.10)
        Loading from cache
    
      - Installing zendframework/zend-soap (2.4.10)
        Loading from cache
    
      - Installing magento/magento2-base (2.0.6)
        Loading from cache
    
      - Installing sebastian/version (1.0.6)
        Loading from cache
    
      - Installing sebastian/recursion-context (1.0.2)
        Loading from cache
    
      - Installing sebastian/exporter (1.2.1)
        Loading from cache
    
      - Installing sebastian/environment (1.3.7)
        Loading from cache
    
      - Installing sebastian/diff (1.4.1)
        Loading from cache
    
      - Installing sebastian/comparator (1.2.0)
        Loading from cache
    
      - Installing symfony/yaml (v2.8.6)
        Loading from cache
    
      - Installing doctrine/instantiator (1.0.5)
        Loading from cache
    
      - Installing phpunit/php-text-template (1.2.1)
        Loading from cache
    
      - Installing phpunit/phpunit-mock-objects (2.3.8)
        Loading from cache
    
      - Installing phpunit/php-timer (1.0.8)
        Loading from cache
    
      - Installing phpunit/php-token-stream (1.4.8)
        Loading from cache
    
      - Installing phpunit/php-file-iterator (1.3.4)
        Loading from cache
    
      - Installing phpunit/php-code-coverage (2.2.4)
        Loading from cache
    
      - Installing phpunit/phpunit (4.1.0)
        Loading from cache
    
      - Installing squizlabs/php_codesniffer (1.5.3)
        Loading from cache
    
      - Installing symfony/dependency-injection (v2.8.6)
        Loading from cache
    
      - Installing symfony/config (v2.8.6)
        Loading from cache
    
      - Installing pdepend/pdepend (2.2.2)
        Loading from cache
    
      - Installing phpmd/phpmd (2.3.3)
        Loading from cache
    
      - Installing league/climate (2.6.1)
        Loading from cache
    
      - Installing sjparkinson/static-review (4.1.1)
        Loading from cache
    
      - Installing symfony/stopwatch (v3.0.6)
        Loading from cache
    
      - Installing fabpot/php-cs-fixer (v1.11.3)
        Loading from cache
    
      - Installing lusitanian/oauth (v0.7.0)
        Loading from cache
    
    magento/framework suggests installing ext-imagick (Use Image Magick >=3.0.0 as an optional alternative image processing library)
    magento/module-theme suggests installing magento/module-theme-sample-data (Sample Data version:100.0.*)
    magento/module-widget suggests installing magento/module-widget-sample-data (Sample Data version:100.0.*)
    magento/module-customer suggests installing magento/module-customer-sample-data (Sample Data version:100.0.*)
    magento/module-tax suggests installing magento/module-tax-sample-data (Sample Data version:100.0.*)
    magento/module-catalog suggests installing magento/module-catalog-sample-data (Sample Data version:100.0.*)
    magento/module-configurable-product suggests installing magento/module-configurable-sample-data (Sample Data version:100.0.*)
    magento/module-configurable-product suggests installing magento/module-product-links-sample-data (Sample Data version:100.0.*)
    magento/module-sales-rule suggests installing magento/module-sales-rule-sample-data (Sample Data version:100.0.*)
    magento/module-catalog-rule suggests installing magento/module-catalog-rule-sample-data (Sample Data version:100.0.*)
    magento/module-msrp suggests installing magento/module-msrp-sample-data (Sample Data version:100.0.*)
    magento/module-grouped-product suggests installing magento/module-grouped-product-sample-data (Sample Data version:100.0.*)
    magento/module-sales suggests installing magento/module-sales-sample-data (Sample Data version:100.0.*)
    magento/module-wishlist suggests installing magento/module-wishlist-sample-data (Sample Data version:100.0.*)
    magento/module-cms suggests installing magento/module-cms-sample-data (Sample Data version:100.0.*)
    magento/module-downloadable suggests installing magento/module-downloadable-sample-data (Sample Data version:100.0.*)
    magento/module-review suggests installing magento/module-review-sample-data (Sample Data version:100.0.*)
    magento/module-swatches suggests installing magento/module-swatches-sample-data (Sample Data version:100.0.*)
    magento/module-sample-data suggests installing magento/sample-data-media (Sample Data version:100.0.*)
    magento/module-offline-shipping suggests installing magento/module-offline-shipping-sample-data (Sample Data version:100.0.*)
    magento/module-bundle suggests installing magento/module-bundle-sample-data (Sample Data version:100.0.*)
    phpseclib/phpseclib suggests installing ext-gmp (Install the GMP (GNU Multiple Precision) extension in order to speed up arbitrary precision integer arithmetic operations.)
    phpseclib/phpseclib suggests installing pear-pear/PHP_Compat (Install PHP_Compat to get phpseclib working on PHP < 4.3.3.)
    symfony/event-dispatcher suggests installing symfony/http-kernel ()
    monolog/monolog suggests installing graylog2/gelf-php (Allow sending log messages to a GrayLog2 server)
    monolog/monolog suggests installing raven/raven (Allow sending log messages to a Sentry server)
    monolog/monolog suggests installing doctrine/couchdb (Allow sending log messages to a CouchDB server)
    monolog/monolog suggests installing ruflin/elastica (Allow sending log messages to an Elastic Search server)
    monolog/monolog suggests installing videlalvaro/php-amqplib (Allow sending log messages to an AMQP server using php-amqplib)
    monolog/monolog suggests installing ext-amqp (Allow sending log messages to an AMQP server (1.0+ required))
    monolog/monolog suggests installing ext-mongo (Allow sending log messages to a MongoDB server)
    monolog/monolog suggests installing aws/aws-sdk-php (Allow sending log messages to AWS services like DynamoDB)
    monolog/monolog suggests installing rollbar/rollbar (Allow sending log messages to Rollbar)
    monolog/monolog suggests installing php-console/php-console (Allow sending log messages to Google Chrome)
    zendframework/zend-validator suggests installing zendframework/zend-db (Zend\Db component)
    zendframework/zend-validator suggests installing zendframework/zend-resources (Translations of validator messages)
    zendframework/zend-validator suggests installing zendframework/zend-session (Zend\Session component)
    zendframework/zend-servicemanager suggests installing ocramius/proxy-manager (ProxyManager 0.5.* to handle lazy initialization of services)
    zendframework/zend-log suggests installing ext-mongo (*)
    zendframework/zend-log suggests installing zendframework/zend-db (Zend\Db component)
    zendframework/zend-log suggests installing zendframework/zend-mail (Zend\Mail component)
    zendframework/zend-math suggests installing ext-gmp (If using the gmp functionality)
    zendframework/zend-math suggests installing ircmaxell/random-lib (Fallback random byte generator for Zend\Math\Rand if OpenSSL/Mcrypt extensions are unavailable)
    zendframework/zend-json suggests installing zendframework/zendxml (To support Zend\Json\Json::fromXml() usage)
    zendframework/zend-code suggests installing doctrine/common (Doctrine\Common >=2.1 for annotation features)
    zendframework/zend-form suggests installing zendframework/zend-captcha (Zend\Captcha component)
    zendframework/zend-form suggests installing zendframework/zendservice-recaptcha (ZendService\ReCaptcha component)
    zendframework/zend-view suggests installing zendframework/zend-authentication (Zend\Authentication component)
    zendframework/zend-view suggests installing zendframework/zend-feed (Zend\Feed component)
    zendframework/zend-view suggests installing zendframework/zend-navigation (Zend\Navigation component)
    zendframework/zend-view suggests installing zendframework/zend-paginator (Zend\Paginator component)
    zendframework/zend-view suggests installing zendframework/zend-permissions-acl (Zend\Permissions\Acl component)
    zendframework/zend-i18n suggests installing zendframework/zend-cache (Zend\Cache component)
    zendframework/zend-i18n suggests installing zendframework/zend-resources (Translation resources)
    zendframework/zend-mvc suggests installing zendframework/zend-authentication (Zend\Authentication component for Identity plugin)
    zendframework/zend-mvc suggests installing zendframework/zend-session (Zend\Session component for FlashMessenger, PRG, and FPRG plugins)
    zendframework/zend-mvc suggests installing zendframework/zend-version (Zend\Version component)
    phpunit/phpunit suggests installing phpunit/php-invoker (~1.1)
    symfony/dependency-injection suggests installing symfony/expression-language (For using expressions in service container configuration)
    symfony/dependency-injection suggests installing symfony/proxy-manager-bridge (Generate service proxies to lazy load them)
    sjparkinson/static-review suggests installing sensiolabs/security-checker (Required for ComposerSecurityReview.)
    lusitanian/oauth suggests installing symfony/http-foundation (Allows using the Symfony Session storage backend.)
    lusitanian/oauth suggests installing predis/predis (Allows using the Redis storage backend.)
    Package fabpot/php-cs-fixer is abandoned, you should avoid using it. Use friendsofphp/php-cs-fixer instead.
    Writing lock file
    Generating autoload files
    Please enter the session save: [files]: files
    Please enter the admin/backend frontname: [admin] admin
    Please enter the default currency code: [EUR]: EUR
    Please enter the locale code: [de_DE]: de_DE
    Please enter the timezone: [Europe/Berlin]: Europe/Berlin
    Please enter the admin username: [admin]: admin
    Please enter the admin password: [password123]: password123
    Please enter the admin's firstname: [John]: John
    Please enter the admin's lastname: [Doe]: Doe
    Please enter the admin's email: [john.doe@example.com]: john.doe@example.com
    Start installation process.
    /usr/bin/env php /tmp/magento/bin/magento setup:install --language='de_DE' --timezone='Europe/Berlin' --db-host='localhost' --db-name='test' --db-user='root' --base-url='http://www.test.tld/' --use-rewrites='1' --use-secure='0' --use-secure-admin='1' --admin-user='admin' --admin-lastname='Doe' --admin-firstname='John' --admin-email='john.doe@example.com' --admin-password='password123' --session-save='files' --backend-frontname='admin' --currency='EUR' --db-password='123456'
    Successfully installed Magento
    Encryption Key:
    File permissions check...
    [Progress: 1 / 309]
    Enabling Maintenance Mode...
    [Progress: 2 / 309]
    Installing deployment configuration...
    [Progress: 3 / 309]
    Installing database schema:
    Schema creation/updates:
    Module 'Magento_Store':
    Installing schema..
    [Progress: 4 / 309]
    Module 'Magento_AdvancedPricingImportExport':
    [Progress: 5 / 309]
    Module 'Magento_Directory':
    Installing schema..
    [Progress: 6 / 309]
    Module 'Magento_Theme':
    Installing schema..
    [Progress: 7 / 309]
    Module 'Magento_Backend':
    [Progress: 8 / 309]
    Module 'Magento_Backup':
    [Progress: 9 / 309]
    Module 'Magento_Eav':
    Installing schema..
    [Progress: 10 / 309]
    Module 'Magento_Customer':
    Installing schema.. Upgrading schema..
    [Progress: 11 / 309]
    Module 'Magento_BundleImportExport':
    [Progress: 12 / 309]
    Module 'Magento_CacheInvalidate':
    [Progress: 13 / 309]
    Module 'Magento_AdminNotification':
    Installing schema..
    [Progress: 14 / 309]
    Module 'Magento_Indexer':
    Installing schema..
    [Progress: 15 / 309]
    Module 'Magento_CatalogImportExport':
    [Progress: 16 / 309]
    Module 'Magento_Cms':
    Installing schema..
    [Progress: 17 / 309]
    Module 'Magento_Rule':
    [Progress: 18 / 309]
    Module 'Magento_Catalog':
    Installing schema.. Upgrading schema..
    [Progress: 19 / 309]
    Module 'Magento_Search':
    Installing schema.. Upgrading schema..
    [Progress: 20 / 309]
    Module 'Magento_CatalogUrlRewrite':
    Installing schema..
    [Progress: 21 / 309]
    Module 'Magento_Widget':
    Installing schema..
    [Progress: 22 / 309]
    Module 'Magento_Quote':
    Installing schema.. Upgrading schema..
    [Progress: 23 / 309]
    Module 'Magento_CheckoutAgreements':
    Installing schema.. Upgrading schema..
    [Progress: 24 / 309]
    Module 'Magento_SalesSequence':
    Installing schema..
    [Progress: 25 / 309]
    Module 'Magento_CmsUrlRewrite':
    [Progress: 26 / 309]
    Module 'Magento_Config':
    Installing schema..
    [Progress: 27 / 309]
    Module 'Magento_ConfigurableImportExport':
    [Progress: 28 / 309]
    Module 'Magento_Msrp':
    [Progress: 29 / 309]
    Module 'Magento_Contact':
    [Progress: 30 / 309]
    Module 'Magento_Cookie':
    [Progress: 31 / 309]
    Module 'Magento_Cron':
    Installing schema..
    [Progress: 32 / 309]
    Module 'Magento_CurrencySymbol':
    [Progress: 33 / 309]
    Module 'Magento_Bundle':
    Installing schema.. Upgrading schema..
    [Progress: 34 / 309]
    Module 'Magento_CustomerImportExport':
    [Progress: 35 / 309]
    Module 'Magento_Deploy':
    [Progress: 36 / 309]
    Module 'Magento_Developer':
    [Progress: 37 / 309]
    Module 'Magento_Dhl':
    [Progress: 38 / 309]
    Module 'Magento_Authorization':
    Installing schema..
    [Progress: 39 / 309]
    Module 'Magento_Downloadable':
    Installing schema..
    [Progress: 40 / 309]
    Module 'Magento_ImportExport':
    Installing schema.. Upgrading schema..
    [Progress: 41 / 309]
    Module 'Magento_Payment':
    [Progress: 42 / 309]
    Module 'Magento_Email':
    Installing schema..
    [Progress: 43 / 309]
    Module 'Magento_User':
    Installing schema.. Upgrading schema..
    [Progress: 44 / 309]
    Module 'Magento_Fedex':
    [Progress: 45 / 309]
    Module 'Magento_Sales':
    Installing schema..
    [Progress: 46 / 309]
    Module 'Magento_CatalogInventory':
    Installing schema..
    [Progress: 47 / 309]
    Module 'Magento_GoogleAnalytics':
    [Progress: 48 / 309]
    Module 'Magento_GoogleOptimizer':
    Installing schema..
    [Progress: 49 / 309]
    Module 'Magento_GroupedImportExport':
    [Progress: 50 / 309]
    Module 'Magento_GroupedProduct':
    [Progress: 51 / 309]
    Module 'Magento_DownloadableImportExport':
    [Progress: 52 / 309]
    Module 'Magento_Checkout':
    [Progress: 53 / 309]
    Module 'Magento_Integration':
    Installing schema.. Upgrading schema..
    [Progress: 54 / 309]
    Module 'Magento_LayeredNavigation':
    [Progress: 55 / 309]
    Module 'Magento_Marketplace':
    [Progress: 56 / 309]
    Module 'Magento_MediaStorage':
    [Progress: 57 / 309]
    Module 'Magento_CatalogRule':
    Installing schema..
    [Progress: 58 / 309]
    Module 'Magento_Multishipping':
    [Progress: 59 / 309]
    Module 'Magento_ConfigurableProduct':
    Installing schema..
    [Progress: 60 / 309]
    Module 'Magento_Newsletter':
    Installing schema..
    [Progress: 61 / 309]
    Module 'Magento_OfflinePayments':
    [Progress: 62 / 309]
    Module 'Magento_SalesRule':
    Installing schema..
    [Progress: 63 / 309]
    Module 'Magento_PageCache':
    [Progress: 64 / 309]
    Module 'Magento_Captcha':
    Installing schema..
    [Progress: 65 / 309]
    Module 'Magento_Paypal':
    Installing schema..
    [Progress: 66 / 309]
    Module 'Magento_Persistent':
    Installing schema..
    [Progress: 67 / 309]
    Module 'Magento_ProductAlert':
    Installing schema..
    [Progress: 68 / 309]
    Module 'Magento_ProductVideo':
    Installing schema..
    [Progress: 69 / 309]
    Module 'Magento_Authorizenet':
    [Progress: 70 / 309]
    Module 'Magento_Reports':
    Installing schema..
    [Progress: 71 / 309]
    Module 'Magento_RequireJs':
    [Progress: 72 / 309]
    Module 'Magento_Review':
    Installing schema..
    [Progress: 73 / 309]
    Module 'Magento_Rss':
    [Progress: 74 / 309]
    Module 'Magento_CatalogRuleConfigurable':
    [Progress: 75 / 309]
    Module 'Magento_Braintree':
    [Progress: 76 / 309]
    Module 'Magento_OfflineShipping':
    Installing schema..
    [Progress: 77 / 309]
    Module 'Magento_GoogleAdwords':
    [Progress: 78 / 309]
    Module 'Magento_SampleData':
    [Progress: 79 / 309]
    Module 'Magento_CatalogSearch':
    Installing schema..
    [Progress: 80 / 309]
    Module 'Magento_SendFriend':
    Installing schema..
    [Progress: 81 / 309]
    Module 'Magento_Ui':
    Installing schema..
    [Progress: 82 / 309]
    Module 'Magento_Sitemap':
    Installing schema..
    [Progress: 83 / 309]
    Module 'Magento_NewRelicReporting':
    Installing schema..
    [Progress: 84 / 309]
    Module 'Magento_Swagger':
    [Progress: 85 / 309]
    Module 'Magento_Swatches':
    Installing schema..
    [Progress: 86 / 309]
    Module 'Magento_Tax':
    Installing schema..
    [Progress: 87 / 309]
    Module 'Magento_TaxImportExport':
    [Progress: 88 / 309]
    Module 'Magento_GiftMessage':
    Installing schema..
    [Progress: 89 / 309]
    Module 'Magento_Translation':
    Installing schema..
    [Progress: 90 / 309]
    Module 'Magento_Shipping':
    [Progress: 91 / 309]
    Module 'Magento_Ups':
    [Progress: 92 / 309]
    Module 'Magento_UrlRewrite':
    Installing schema..
    [Progress: 93 / 309]
    Module 'Magento_EncryptionKey':
    [Progress: 94 / 309]
    Module 'Magento_Usps':
    [Progress: 95 / 309]
    Module 'Magento_Variable':
    Installing schema..
    [Progress: 96 / 309]
    Module 'Magento_Version':
    [Progress: 97 / 309]
    Module 'Magento_Webapi':
    [Progress: 98 / 309]
    Module 'Magento_WebapiSecurity':
    [Progress: 99 / 309]
    Module 'Magento_Weee':
    Installing schema..
    [Progress: 100 / 309]
    Module 'Magento_CatalogWidget':
    [Progress: 101 / 309]
    Module 'Magento_Wishlist':
    Installing schema..
    [Progress: 102 / 309]
    Schema post-updates:
    Module 'Magento_Store':
    [Progress: 103 / 309]
    Module 'Magento_AdvancedPricingImportExport':
    [Progress: 104 / 309]
    Module 'Magento_Directory':
    [Progress: 105 / 309]
    Module 'Magento_Theme':
    [Progress: 106 / 309]
    Module 'Magento_Backend':
    [Progress: 107 / 309]
    Module 'Magento_Backup':
    [Progress: 108 / 309]
    Module 'Magento_Eav':
    [Progress: 109 / 309]
    Module 'Magento_Customer':
    [Progress: 110 / 309]
    Module 'Magento_BundleImportExport':
    [Progress: 111 / 309]
    Module 'Magento_CacheInvalidate':
    [Progress: 112 / 309]
    Module 'Magento_AdminNotification':
    [Progress: 113 / 309]
    Module 'Magento_Indexer':
    Running recurring..
    [Progress: 114 / 309]
    Module 'Magento_CatalogImportExport':
    [Progress: 115 / 309]
    Module 'Magento_Cms':
    [Progress: 116 / 309]
    Module 'Magento_Rule':
    [Progress: 117 / 309]
    Module 'Magento_Catalog':
    [Progress: 118 / 309]
    Module 'Magento_Search':
    [Progress: 119 / 309]
    Module 'Magento_CatalogUrlRewrite':
    [Progress: 120 / 309]
    Module 'Magento_Widget':
    [Progress: 121 / 309]
    Module 'Magento_Quote':
    [Progress: 122 / 309]
    Module 'Magento_CheckoutAgreements':
    [Progress: 123 / 309]
    Module 'Magento_SalesSequence':
    [Progress: 124 / 309]
    Module 'Magento_CmsUrlRewrite':
    [Progress: 125 / 309]
    Module 'Magento_Config':
    [Progress: 126 / 309]
    Module 'Magento_ConfigurableImportExport':
    [Progress: 127 / 309]
    Module 'Magento_Msrp':
    [Progress: 128 / 309]
    Module 'Magento_Contact':
    [Progress: 129 / 309]
    Module 'Magento_Cookie':
    [Progress: 130 / 309]
    Module 'Magento_Cron':
    [Progress: 131 / 309]
    Module 'Magento_CurrencySymbol':
    [Progress: 132 / 309]
    Module 'Magento_Bundle':
    [Progress: 133 / 309]
    Module 'Magento_CustomerImportExport':
    [Progress: 134 / 309]
    Module 'Magento_Deploy':
    [Progress: 135 / 309]
    Module 'Magento_Developer':
    [Progress: 136 / 309]
    Module 'Magento_Dhl':
    [Progress: 137 / 309]
    Module 'Magento_Authorization':
    [Progress: 138 / 309]
    Module 'Magento_Downloadable':
    [Progress: 139 / 309]
    Module 'Magento_ImportExport':
    [Progress: 140 / 309]
    Module 'Magento_Payment':
    [Progress: 141 / 309]
    Module 'Magento_Email':
    [Progress: 142 / 309]
    Module 'Magento_User':
    [Progress: 143 / 309]
    Module 'Magento_Fedex':
    [Progress: 144 / 309]
    Module 'Magento_Sales':
    [Progress: 145 / 309]
    Module 'Magento_CatalogInventory':
    [Progress: 146 / 309]
    Module 'Magento_GoogleAnalytics':
    [Progress: 147 / 309]
    Module 'Magento_GoogleOptimizer':
    [Progress: 148 / 309]
    Module 'Magento_GroupedImportExport':
    [Progress: 149 / 309]
    Module 'Magento_GroupedProduct':
    [Progress: 150 / 309]
    Module 'Magento_DownloadableImportExport':
    [Progress: 151 / 309]
    Module 'Magento_Checkout':
    [Progress: 152 / 309]
    Module 'Magento_Integration':
    [Progress: 153 / 309]
    Module 'Magento_LayeredNavigation':
    [Progress: 154 / 309]
    Module 'Magento_Marketplace':
    [Progress: 155 / 309]
    Module 'Magento_MediaStorage':
    [Progress: 156 / 309]
    Module 'Magento_CatalogRule':
    [Progress: 157 / 309]
    Module 'Magento_Multishipping':
    [Progress: 158 / 309]
    Module 'Magento_ConfigurableProduct':
    [Progress: 159 / 309]
    Module 'Magento_Newsletter':
    [Progress: 160 / 309]
    Module 'Magento_OfflinePayments':
    [Progress: 161 / 309]
    Module 'Magento_SalesRule':
    [Progress: 162 / 309]
    Module 'Magento_PageCache':
    [Progress: 163 / 309]
    Module 'Magento_Captcha':
    [Progress: 164 / 309]
    Module 'Magento_Paypal':
    [Progress: 165 / 309]
    Module 'Magento_Persistent':
    [Progress: 166 / 309]
    Module 'Magento_ProductAlert':
    [Progress: 167 / 309]
    Module 'Magento_ProductVideo':
    [Progress: 168 / 309]
    Module 'Magento_Authorizenet':
    [Progress: 169 / 309]
    Module 'Magento_Reports':
    [Progress: 170 / 309]
    Module 'Magento_RequireJs':
    [Progress: 171 / 309]
    Module 'Magento_Review':
    [Progress: 172 / 309]
    Module 'Magento_Rss':
    [Progress: 173 / 309]
    Module 'Magento_CatalogRuleConfigurable':
    [Progress: 174 / 309]
    Module 'Magento_Braintree':
    [Progress: 175 / 309]
    Module 'Magento_OfflineShipping':
    [Progress: 176 / 309]
    Module 'Magento_GoogleAdwords':
    [Progress: 177 / 309]
    Module 'Magento_SampleData':
    [Progress: 178 / 309]
    Module 'Magento_CatalogSearch':
    [Progress: 179 / 309]
    Module 'Magento_SendFriend':
    [Progress: 180 / 309]
    Module 'Magento_Ui':
    [Progress: 181 / 309]
    Module 'Magento_Sitemap':
    [Progress: 182 / 309]
    Module 'Magento_NewRelicReporting':
    [Progress: 183 / 309]
    Module 'Magento_Swagger':
    [Progress: 184 / 309]
    Module 'Magento_Swatches':
    [Progress: 185 / 309]
    Module 'Magento_Tax':
    [Progress: 186 / 309]
    Module 'Magento_TaxImportExport':
    [Progress: 187 / 309]
    Module 'Magento_GiftMessage':
    [Progress: 188 / 309]
    Module 'Magento_Translation':
    [Progress: 189 / 309]
    Module 'Magento_Shipping':
    [Progress: 190 / 309]
    Module 'Magento_Ups':
    [Progress: 191 / 309]
    Module 'Magento_UrlRewrite':
    [Progress: 192 / 309]
    Module 'Magento_EncryptionKey':
    [Progress: 193 / 309]
    Module 'Magento_Usps':
    [Progress: 194 / 309]
    Module 'Magento_Variable':
    [Progress: 195 / 309]
    Module 'Magento_Version':
    [Progress: 196 / 309]
    Module 'Magento_Webapi':
    [Progress: 197 / 309]
    Module 'Magento_WebapiSecurity':
    [Progress: 198 / 309]
    Module 'Magento_Weee':
    [Progress: 199 / 309]
    Module 'Magento_CatalogWidget':
    [Progress: 200 / 309]
    Module 'Magento_Wishlist':
    [Progress: 201 / 309]
    [Progress: 202 / 309]
    Installing user configuration...
    [Progress: 203 / 309]
    Enabling caches:
    Current status:
    Array
    (
        [config] => 1
        [layout] => 1
        [block_html] => 1
        [collections] => 1
        [reflection] => 1
        [db_ddl] => 1
        [eav] => 1
        [config_integration] => 1
        [config_integration_api] => 1
        [full_page] => 1
        [translate] => 1
        [config_webservice] => 1
    )
    
    [Progress: 204 / 309]
    Installing data...
    Data install/update:
    Module 'Magento_Store':
    [Progress: 205 / 309]
    Module 'Magento_AdvancedPricingImportExport':
    [Progress: 206 / 309]
    Module 'Magento_Directory':
    Installing data..
    [Progress: 207 / 309]
    Module 'Magento_Theme':
    Installing data..
    [Progress: 208 / 309]
    Module 'Magento_Backend':
    [Progress: 209 / 309]
    Module 'Magento_Backup':
    [Progress: 210 / 309]
    Module 'Magento_Eav':
    Installing data..
    [Progress: 211 / 309]
    Module 'Magento_Customer':
    Installing data.. Upgrading data..
    [Progress: 212 / 309]
    Module 'Magento_BundleImportExport':
    [Progress: 213 / 309]
    Module 'Magento_CacheInvalidate':
    [Progress: 214 / 309]
    Module 'Magento_AdminNotification':
    [Progress: 215 / 309]
    Module 'Magento_Indexer':
    Installing data..
    [Progress: 216 / 309]
    Module 'Magento_CatalogImportExport':
    [Progress: 217 / 309]
    Module 'Magento_Cms':
    Installing data..
    [Progress: 218 / 309]
    Module 'Magento_Rule':
    [Progress: 219 / 309]
    Module 'Magento_Catalog':
    Installing data.. Upgrading data..
    [Progress: 220 / 309]
    Module 'Magento_Search':
    [Progress: 221 / 309]
    Module 'Magento_CatalogUrlRewrite':
    Installing data..
    [Progress: 222 / 309]
    Module 'Magento_Widget':
    Installing data..
    [Progress: 223 / 309]
    Module 'Magento_Quote':
    Installing data..
    [Progress: 224 / 309]
    Module 'Magento_CheckoutAgreements':
    [Progress: 225 / 309]
    Module 'Magento_SalesSequence':
    Installing data..
    [Progress: 226 / 309]
    Module 'Magento_CmsUrlRewrite':
    [Progress: 227 / 309]
    Module 'Magento_Config':
    Installing data..
    [Progress: 228 / 309]
    Module 'Magento_ConfigurableImportExport':
    [Progress: 229 / 309]
    Module 'Magento_Msrp':
    Installing data..
    [Progress: 230 / 309]
    Module 'Magento_Contact':
    [Progress: 231 / 309]
    Module 'Magento_Cookie':
    [Progress: 232 / 309]
    Module 'Magento_Cron':
    [Progress: 233 / 309]
    Module 'Magento_CurrencySymbol':
    [Progress: 234 / 309]
    Module 'Magento_Bundle':
    Installing data..
    [Progress: 235 / 309]
    Module 'Magento_CustomerImportExport':
    [Progress: 236 / 309]
    Module 'Magento_Deploy':
    [Progress: 237 / 309]
    Module 'Magento_Developer':
    [Progress: 238 / 309]
    Module 'Magento_Dhl':
    Installing data..
    [Progress: 239 / 309]
    Module 'Magento_Authorization':
    Installing data..
    [Progress: 240 / 309]
    Module 'Magento_Downloadable':
    Installing data..
    [Progress: 241 / 309]
    Module 'Magento_ImportExport':
    [Progress: 242 / 309]
    Module 'Magento_Payment':
    [Progress: 243 / 309]
    Module 'Magento_Email':
    [Progress: 244 / 309]
    Module 'Magento_User':
    Upgrading data..
    [Progress: 245 / 309]
    Module 'Magento_Fedex':
    Installing data..
    [Progress: 246 / 309]
    Module 'Magento_Sales':
    Installing data.. Upgrading data..
    [Progress: 247 / 309]
    Module 'Magento_CatalogInventory':
    Installing data..
    [Progress: 248 / 309]
    Module 'Magento_GoogleAnalytics':
    [Progress: 249 / 309]
    Module 'Magento_GoogleOptimizer':
    [Progress: 250 / 309]
    Module 'Magento_GroupedImportExport':
    [Progress: 251 / 309]
    Module 'Magento_GroupedProduct':
    Installing data..
    [Progress: 252 / 309]
    Module 'Magento_DownloadableImportExport':
    [Progress: 253 / 309]
    Module 'Magento_Checkout':
    Installing data..
    [Progress: 254 / 309]
    Module 'Magento_Integration':
    [Progress: 255 / 309]
    Module 'Magento_LayeredNavigation':
    [Progress: 256 / 309]
    Module 'Magento_Marketplace':
    [Progress: 257 / 309]
    Module 'Magento_MediaStorage':
    [Progress: 258 / 309]
    Module 'Magento_CatalogRule':
    Installing data..
    [Progress: 259 / 309]
    Module 'Magento_Multishipping':
    [Progress: 260 / 309]
    Module 'Magento_ConfigurableProduct':
    Installing data..
    [Progress: 261 / 309]
    Module 'Magento_Newsletter':
    [Progress: 262 / 309]
    Module 'Magento_OfflinePayments':
    [Progress: 263 / 309]
    Module 'Magento_SalesRule':
    Installing data..
    [Progress: 264 / 309]
    Module 'Magento_PageCache':
    [Progress: 265 / 309]
    Module 'Magento_Captcha':
    [Progress: 266 / 309]
    Module 'Magento_Paypal':
    Installing data..
    [Progress: 267 / 309]
    Module 'Magento_Persistent':
    [Progress: 268 / 309]
    Module 'Magento_ProductAlert':
    [Progress: 269 / 309]
    Module 'Magento_ProductVideo':
    Upgrading data..
    [Progress: 270 / 309]
    Module 'Magento_Authorizenet':
    [Progress: 271 / 309]
    Module 'Magento_Reports':
    Installing data..
    [Progress: 272 / 309]
    Module 'Magento_RequireJs':
    [Progress: 273 / 309]
    Module 'Magento_Review':
    Installing data..
    [Progress: 274 / 309]
    Module 'Magento_Rss':
    [Progress: 275 / 309]
    Module 'Magento_CatalogRuleConfigurable':
    [Progress: 276 / 309]
    Module 'Magento_Braintree':
    [Progress: 277 / 309]
    Module 'Magento_OfflineShipping':
    [Progress: 278 / 309]
    Module 'Magento_GoogleAdwords':
    [Progress: 279 / 309]
    Module 'Magento_SampleData':
    Installing data..
    [Progress: 280 / 309]
    Module 'Magento_CatalogSearch':
    Installing data..
    [Progress: 281 / 309]
    Module 'Magento_SendFriend':
    [Progress: 282 / 309]
    Module 'Magento_Ui':
    [Progress: 283 / 309]
    Module 'Magento_Sitemap':
    [Progress: 284 / 309]
    Module 'Magento_NewRelicReporting':
    [Progress: 285 / 309]
    Module 'Magento_Swagger':
    [Progress: 286 / 309]
    Module 'Magento_Swatches':
    Installing data..
    [Progress: 287 / 309]
    Module 'Magento_Tax':
    Installing data.. Upgrading data..
    [Progress: 288 / 309]
    Module 'Magento_TaxImportExport':
    [Progress: 289 / 309]
    Module 'Magento_GiftMessage':
    Installing data..
    [Progress: 290 / 309]
    Module 'Magento_Translation':
    [Progress: 291 / 309]
    Module 'Magento_Shipping':
    [Progress: 292 / 309]
    Module 'Magento_Ups':
    [Progress: 293 / 309]
    Module 'Magento_UrlRewrite':
    [Progress: 294 / 309]
    Module 'Magento_EncryptionKey':
    [Progress: 295 / 309]
    Module 'Magento_Usps':
    Installing data..
    [Progress: 296 / 309]
    Module 'Magento_Variable':
    [Progress: 297 / 309]
    Module 'Magento_Version':
    [Progress: 298 / 309]
    Module 'Magento_Webapi':
    [Progress: 299 / 309]
    Module 'Magento_WebapiSecurity':
    [Progress: 300 / 309]
    Module 'Magento_Weee':
    Installing data..
    [Progress: 301 / 309]
    Module 'Magento_CatalogWidget':
    [Progress: 302 / 309]
    Module 'Magento_Wishlist':
    [Progress: 303 / 309]
    [Progress: 304 / 309]
    Installing admin user...
    [Progress: 305 / 309]
    Caches clearing:
    Cache cleared successfully
    [Progress: 306 / 309]
    Disabling Maintenance Mode:
    [Progress: 307 / 309]
    Post installation file permissions check...
    For security, remove write permissions from these directories: '/tmp/magento/app/etc'
    [Progress: 308 / 309]
    Write installation date...
    [Progress: 309 / 309]
    [SUCCESS]: Magento installation complete.
    [SUCCESS]: Magento Admin URI: /admin
    Install sample data? [y]: n
    Reindex all after installation
    Customer Grid index has been rebuilt successfully in 00:00:00
    Category Products index has been rebuilt successfully in 00:00:00
    Product Categories index has been rebuilt successfully in 00:00:00
    Product Price index has been rebuilt successfully in 00:00:00
    Product EAV index has been rebuilt successfully in 00:00:00
    Stock index has been rebuilt successfully in 00:00:00
    Catalog Rule Product index has been rebuilt successfully in 00:00:00
    Catalog Product Rule index has been rebuilt successfully in 00:00:00
    Catalog Search index has been rebuilt successfully in 00:00:00
    Successfully installed magento
    
Note that I left out two parameters `--installSampleData` and `--replaceHtaccessFile` which as far as I see should behave the same when they are not specified.

At the end of the output, I get asked:

>  Install sample data? [y] 

But I never get asked: 

> Write BaseURL to .htaccess file? [n]

**Comment by ktomk** [comment]
@mzeis: Problem description was fine. Stable build 1.1.14 of the phar is broken, it's not updated to it's own code. Should offer 2.0.7 with first version but phar from the website does not (as your great log shows). I try to reproduce it with the source version and will report back. Thanks for the update.

**Comment by ktomk** [comment]
@mzeis: Reproduced and fixed. Is now part of the development version. Our automatic build is currently broken, you can try the source version and it is also easy to create the phar from source by executing the `./build.sh` script. Thanks again for taking the time to report this and your patience.
