### ISSUE TITLE
xtento Product feed export is causing error when working with crons (M2)

### ISSUE THREAD

**Issue by redboxmarcins** [netz98/n98-magerun2#201]
If you create any export profile then after running any cron related command you get

```
                
  Cronjob List  
                



                         
  [ErrorException]       
  Undefined index: name  
                         


Exception trace:
 () at phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php:67
 Composer\Util\ErrorHandler::handle() at phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php:67
 N98\Magento\Command\System\Cron\AbstractCronCommand->getJobs() at phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/System/Cron/ListCommand.php:42
 N98\Magento\Command\System\Cron\ListCommand->execute() at phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Command/AbstractMagentoCommand.php:432
 N98\Magento\Command\AbstractMagentoCommand->run() at phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Symfony/Component/Console/Application.php:882
 Symfony\Component\Console\Application->doRunCommand() at phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Application.php:524
 N98\Magento\Application->doRun() at phar:///usr/local/bin/n98-magerun2/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at phar:///usr/local/bin/n98-magerun2/src/N98/Magento/Application.php:556
 N98\Magento\Application->run() at /usr/local/bin/n98-magerun2:8


sys:cron:list [--format[="..."]]
```

**Comment by redboxmarcins** [comment]
Looks like it is Magento 2 problem not your tool https://github.com/magento/magento2/issues/4719

**Comment by ktomk** [comment]
@redboxmarcins: Even this might qualify as a flaw in Magento2, this flaw should not cause the undefined index error in N98-Magerun2. Thanks for reporting this issue, it has been addressed with a patch in the development branch and when our automatic build works again will be part of the unstable version. Thanks again for the report!

**Comment by erikhansen** [comment]
I just experienced this on a Magento 2.1.5 site with the Xtento_ProductExport and Xtento_XtCore modules installed. Any idea when this fix will make it into the next release?

**Comment by erikhansen** [comment]
Never mind. I downloaded the latest release of Magerun2 and I'm still getting the error, even after disabling the Xtento extensions, so it looks like my error is related to some other extension installed on my site:

```
 Notice: Undefined index: name in phar:///var/www/stage/releases/20170323223437/n98-magerun2-latest.phar/src/N98/Magento/Command/System/Cron/AbstractCronCommand.php on line   
  97 
```

I'll open a new issue if I find a consistent way to reproduce the issue.

**Comment by ajpevers** [comment]
@erikhansen: A consistent way to reproduce it is to enter a nonexistent crontab entry in the `core_config_data` table:

```
INSERT INTO `core_config_data` (`scope`, `scope_id`, `path`, `value`)
VALUES
	('default', 0, 'crontab/default/jobs/i_do_not_exist/schedule/cron_expr', '* * * * *');
```

Then flush config cache.

In my opinion it would be best if this tool would be able to deal with this faulty config. After all it is a tool designed for development. When multiple developers are working with te same database it is very likely that the code bases of the different developers don't match and this error will occur. The only solution then is to remove the DB entry and annoy your colleague who needs it for his development. Magento will also still run all jobs except the faulty one with the faulty config in place. So best to behave the same with this tool. I'll write a PR for this.
